name = "jerseyflow-api-v1"
main = "src/index.ts"
compatibility_date = "2024-11-01"
account_id = "5b5194deaa35116098d3f45dee890e17"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "jerseyflow_production_jwt_secret_key_2026"
DEFAULT_UPI_ID = "jerseyflow@upi"
STORE_NAME = "JerseyFlow Store"
WHATSAPP_VERIFY_TOKEN = "jerseyflow_webhook_secret"
WHATSAPP_PHONE_NUMBER_ID = "1266379983225569"
WHATSAPP_BUSINESS_ACCOUNT_ID = "1707833980272775"
TELEGRAM_BOT_TOKEN = "8958059583:AAH8J6qI88pHB85pX3QPwebMIyvvUyrJPoI"

[[d1_databases]]
binding = "DB"
database_name = "jerseyflow-db"
database_id = "825209cd-dd08-4c48-bb37-50dc35428e83"
