"use client";

import { Instagram, TrendingUp, Eye, ShoppingCart, DollarSign, ExternalLink, MessageSquare, ArrowUpRight } from "lucide-react";

export default function CampaignAnalyticsPage() {
  const campaigns = [
    {
      id: "camp_1",
      name: "Instagram Reel #27 — New Lakers Home Kit",
      source: "instagram",
      medium: "reel_comment",
      utmUrl: "https://jerseyflow.com/products/mu-001?source=instagram&campaign=reel_27",
      visitors: 1240,
      productViews: 483,
      waOrdersInitiated: 41,
      completedOrders: 17,
      revenue: 25483,
      conversionRate: 3.5,
    },
    {
      id: "camp_2",
      name: "Instagram DM Automation — Barca Away Price Inquiry",
      source: "instagram",
      medium: "dm_keyword",
      utmUrl: "https://jerseyflow.com/products/bar-004?source=instagram&campaign=dm_barca",
      visitors: 850,
      productViews: 320,
      waOrdersInitiated: 28,
      completedOrders: 12,
      revenue: 13188,
      conversionRate: 3.75,
    },
    {
      id: "camp_3",
      name: "Instagram Bio Link — Digital Showroom Showcase",
      source: "instagram",
      medium: "bio_link",
      utmUrl: "https://jerseyflow.com/products?source=instagram&campaign=bio",
      visitors: 2150,
      productViews: 1100,
      waOrdersInitiated: 62,
      completedOrders: 29,
      revenue: 31871,
      conversionRate: 2.63,
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <Instagram className="w-6 h-6 text-pink-500" />
            <span>Instagram Campaign Attribution & Analytics</span>
          </h1>
          <p className="text-sm text-[#a1a1aa] mt-0.5">
            Track visitors, product views, and WhatsApp orders generated by specific Reels, Comments, and DMs.
          </p>
        </div>
      </div>

      {/* TOP SUMMARY CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="glass-card p-5">
          <p className="text-xs text-[#a1a1aa] font-mono">Instagram Visitors</p>
          <p className="text-2xl font-bold text-white mt-1">4,240</p>
          <p className="text-[11px] text-emerald-400 font-mono mt-1">+24% from last week</p>
        </div>
        <div className="glass-card p-5">
          <p className="text-xs text-[#a1a1aa] font-mono">Product Detail Views</p>
          <p className="text-2xl font-bold text-white mt-1">1,903</p>
          <p className="text-[11px] text-emerald-400 font-mono mt-1">44.8% view rate</p>
        </div>
        <div className="glass-card p-5">
          <p className="text-xs text-[#a1a1aa] font-mono">WhatsApp Sales Initiated</p>
          <p className="text-2xl font-bold text-white mt-1">131</p>
          <p className="text-[11px] text-emerald-400 font-mono mt-1">6.8% intent rate</p>
        </div>
        <div className="glass-card p-5 border-emerald-500/30">
          <p className="text-xs text-emerald-400 font-mono">Campaign Revenue</p>
          <p className="text-2xl font-black text-white mt-1">₹70,542</p>
          <p className="text-[11px] text-[#a1a1aa] font-mono mt-1">58 Paid Orders</p>
        </div>
      </div>

      {/* CAMPAIGN PERFORMANCE TABLE */}
      <div className="glass-card p-6">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-white/10 text-[#a1a1aa]">
                <th className="pb-3 font-medium">Campaign / Reel Name</th>
                <th className="pb-3 font-medium">Medium</th>
                <th className="pb-3 font-medium">Visitors</th>
                <th className="pb-3 font-medium">Views</th>
                <th className="pb-3 font-medium">WA Orders</th>
                <th className="pb-3 font-medium">Paid Orders</th>
                <th className="pb-3 font-medium">Revenue</th>
                <th className="pb-3 font-medium text-right">Conv. Rate</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {campaigns.map((c) => (
                <tr key={c.id} className="hover:bg-white/5 transition-colors">
                  <td className="py-4">
                    <p className="font-semibold text-white">{c.name}</p>
                    <a
                      href={c.utmUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[10px] text-emerald-400 hover:underline font-mono inline-flex items-center gap-1 mt-0.5"
                    >
                      <span>UTM Link</span>
                      <ArrowUpRight className="w-3 h-3" />
                    </a>
                  </td>
                  <td className="py-4">
                    <span className="px-2 py-0.5 rounded bg-pink-500/10 text-pink-400 font-mono text-[10px] font-bold">
                      {c.medium}
                    </span>
                  </td>
                  <td className="py-4 font-mono font-bold text-white">{c.visitors}</td>
                  <td className="py-4 font-mono text-white">{c.productViews}</td>
                  <td className="py-4 font-mono font-bold text-emerald-400">{c.waOrdersInitiated}</td>
                  <td className="py-4 font-mono font-bold text-[#f4f4f5]">{c.completedOrders}</td>
                  <td className="py-4 font-mono font-bold text-white">₹{c.revenue.toLocaleString("en-IN")}</td>
                  <td className="py-4 text-right font-mono font-bold text-emerald-400">{c.conversionRate}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
